import JSZip from 'jszip';
import { saveAs } from 'file-saver';

/**
 * Export the GrapesJS editor project as a ZIP file
 * @param {Object} editor - The GrapesJS editor instance
 */
export const handleExport = async (editor) => {
  if (!editor) {
    console.error('[Export] Editor instance not available');
    return;
  }

  try {
    console.log('[Export] Starting export process...');

    // Extract HTML and CSS from GrapesJS
    const html = editor.getHtml();
    const css = editor.getCss();

    // Create the complete HTML document with boilerplate
    const fullHtml = `<!DOCTYPE html>
<html lang="tr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="WebEditor ile oluşturulan web sitesi">
  <title>Web Sitem</title>
  
  <!-- Tailwind CSS -->
  <script src="https://cdn.tailwindcss.com"></script>
  
  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
  
  <!-- Custom CSS -->
  <link rel="stylesheet" href="css/style.css">
  
  <!-- Alpine.js for interactivity -->
  <script defer src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"></script>
</head>
<body class="font-sans antialiased text-gray-900 bg-gray-100">
${html}

<!-- Generated by WebEditor -->
</body>
</html>`;

    // Create CSS content
    const fullCss = `/* 
  Generated by WebEditor 
  Upload these files to your server to publish your website.
*/

/* Base styles */
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

/* Custom scrollbar */
::-webkit-scrollbar {
  width: 8px;
  height: 8px;
}

::-webkit-scrollbar-track {
  background: #f1f1f1;
  border-radius: 4px;
}

::-webkit-scrollbar-thumb {
  background: #888;
  border-radius: 4px;
}

::-webkit-scrollbar-thumb:hover {
  background: #555;
}

/* GrapesJS generated CSS */
${css}
`;

    // Create README content
    const readmeContent = `WebEditor ile Oluşturulan Website Projesi
==========================================

Bu proje WebEditor uygulaması kullanılarak oluşturulmuştur.

Dosya Yapısı:
--------------
- index.html    : Ana HTML dosyası
- css/style.css  : Özel stiller
- assets/        : Resim ve medya dosyaları

Kurulum:
--------
1. Tüm dosyaları web sunucunuza yükleyin
2. index.html dosyasını açın
3. Website yayında!

Not: Bu proje Tailwind CSS ve Alpine.js kullanmaktadır.
Bu kütüphaneler CDN üzerinden yüklendiği için internet bağlantısı gerektirir.

Oluşturulma Tarihi: ${new Date().toLocaleDateString('tr-TR')}
`;

    // Create ZIP file
    const zip = new JSZip();

    // Add index.html
    zip.file('index.html', fullHtml);

    // Create css folder and add style.css
    zip.file('css/style.css', fullCss);

    // Add README
    zip.file('README.txt', readmeContent);

    // Generate ZIP file
    console.log('[Export] Generating ZIP file...');
    const content = await zip.generateAsync({ type: 'blob' });

    // Generate filename with timestamp
    const timestamp = new Date().toISOString().slice(0, 10);
    const filename = `WebSite_Export_${timestamp}.zip`;

    // Trigger download
    saveAs(content, filename);

    console.log(`[Export] Successfully exported as ${filename}`);
    console.log(`[Export] HTML size: ${fullHtml.length} bytes`);
    console.log(`[Export] CSS size: ${fullCss.length} bytes`);

    // Show success feedback
    editor.Notifier.success({
      message: `Proje başarıyla indirildi: ${filename}`,
      timeout: 3000
    });

  } catch (error) {
    console.error('[Export] Error during export:', error);
    editor.Notifier.error({
      message: 'Dışa aktarma sırasında bir hata oluştu.',
      timeout: 3000
    });
  }
};

export default handleExport;
